version: '3'
services:

  bitcoind:
    image: kylemanna/bitcoind:latest
    volumes:
      - bitcoin-testnet-data:/bitcoin
      - "./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf"
    expose:
      - "18332"
  tor:
    build: ./tor
    image: tor:latest
    user: "1001"
    ports:
      - "9050:9050"
      - "9051:9051"
  ntumblebit:
    build: ./ntumblebit
    image: ntumblebit:latest
    user: "1001"
    links:
      - bitcoind
    depends_on:
      - tor

volumes:
  bitcoin-testnet-data:

