version: '2'
services:

  bitcoind:
    image: kylemanna/bitcoind:latest
    volumes:
      - bitcoin-testnet-data:/bitcoin
      - "./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf"
    expose:
      - "18332"
    networks:
      ntumblebit:
        ipv4_address: 10.5.0.5
  tor:
    build: ./tor
    image: tor:latest
    user: "1001"
    ports:
      - "9050:9050"
      - "9051:9051"
    networks:
      ntumblebit:
        ipv4_address: 10.5.0.6
  ntumblebit:
    build: ./ntumblebit
    image: ntumblebit:latest
    user: "1001"
    networks:
      ntumblebit:
        ipv4_address: 10.5.0.7
    depends_on:
      - bitcoind
      - tor

volumes:
  bitcoin-testnet-data:

networks:
  ntumblebit:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
